# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-19 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updata',
            new_name='UpdateModel',
        ),
    ]
